name: CMake

on: [pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Build Benchmark library
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        git clone https://github.com/google/benchmark.git
        git clone https://github.com/google/googletest.git benchmark/googletest
        cd benchmark
        cmake -E make_directory "build"
        cmake -E chdir "build" cmake -DCMAKE_BUILD_TYPE=Release ../
        cmake --build "build" --config Release --parallel 4

    - name: Create Solution Build Environment
      run: |
        cmake -E make_directory ${{github.workspace}}/build_solution

    - name: Configure Solution CMake
      shell: bash
      working-directory: ${{github.workspace}}/build_solution
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=-I${{github.workspace}}/benchmark/include -DCMAKE_LIBRARY_PATH=${{github.workspace}}/benchmark/build/src

    - name: Build Solution
      working-directory: ${{github.workspace}}/build_solution
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --parallel 2


    - name: Create Baseline Build Environment
      run: |
        cd ${{github.workspace}}/
        ls -l
        git checkout ${{ github.event.pull_request.base.ref }}
        cmake -E make_directory ${{github.workspace}}/build_baseline

    - name: Configure Baseline CMake
      shell: bash
      working-directory: ${{github.workspace}}/build_baseline
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=-I${{github.workspace}}/benchmark/include -DCMAKE_LIBRARY_PATH=${{github.workspace}}/benchmark/build/src

    - name: Build Baseline
      working-directory: ${{github.workspace}}/build_baseline
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --parallel 2

       
    - name: Benchmark
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
         ./build_baseline/lab
         ./build_solution/lab
