name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Create Solution Build Environment
      run: |
        cmake -E make_directory ${{github.workspace}}/build_solution

    - name: Configure Solution CMake
      shell: bash
      working-directory: ${{github.workspace}}/build_solution
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build Solution
      working-directory: ${{github.workspace}}/build_solution
      shell: bash
      run: cmake --build . --config $BUILD_TYPE


    - name: Create Baseline Build Environment
      run: |
        cd ${{github.workspace}}/
        ls -l
        git checkout ${{ github.event.base_ref }}
        cmake -E make_directory ${{github.workspace}}/build_baseline

    - name: Configure Baseline CMake
      shell: bash
      working-directory: ${{github.workspace}}/build_baseline
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build Baseline
      working-directory: ${{github.workspace}}/build_baseline
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

       
    - name: Benchmark
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
         ./build_baseline/lab
         ./build_solution/lab
